@startuml vm-setup
skinparam monochrome true
skinparam defaulttextalignment center

frame "Virtual Network" as VNET {
  frame "Subnet" as subnet {
    component "Virtual Machine\ngitea" as VM1 {
      database "Managed\nDisk" as disk1
    }

    component "Virtual Machine\ndrone" as VM2 {
      database "Managed\nDisk" as disk2
    }
  }
}

database "Azure\nPostgreSQL" as psql
VM1 -- psql
@enduml

@startuml rp-setup
skinparam monochrome true
skinparam defaulttextalignment center

component "Virtual Machine" as VM1 {
  component Docker as docker1 {
    artifact "service A" as servicea
    artifact "service B" as serviceb
    artifact "traefik:latest" as traefik
  }
  traefik -- servicea: internal port\n<i>:3000
  traefik -- serviceb: <i>:3030
}
note left of VM1
  1x public IP
  service-a.mydomain.com
  service-b.io
end note

interface "service-a.mydomain.com <i>:80,443" as SSLa
interface "service-b.io <i>:80,443" as SSLb
interface "Traefik dashboard <i>:80,443" as SSL_traefik

SSLa -down- traefik
SSLb -down- traefik
SSL_traefik -down- traefik

@enduml

@startuml vm-gitea
skinparam monochrome true
skinparam defaulttextalignment center

component "Virtual Machine\ngitea" as VM1 {
  component Docker as docker1 {
    artifact "gitea/gitea:latest" as gitea
    artifact "traefik:latest" as traefik_git
    artifact "plantuml/plantuml-server:jetty" as plantuml
    artifact "docker daemon" as docker
  }
  database "Managed\nDisk" as disk1
  gitea .. disk1: /data/volumes/gitea
  traefik_git .. disk1: /data/volumes/traefik
  traefik_git .left. docker: /var/run/docker.sock
  traefik_git -- gitea: 3000
  traefik_git -- plantuml: 8080
}

database "Azure\nPostgreSQL" as psql
interface "Gitea Website <i>:80,443" as SSL_git
interface "Gitea git <i>:22" as SSH_git
interface "Traefik dashboard <i>:80,443" as SSL_traefik
interface "PlantUML <i>:80,443" as SSL_plantuml

psql -up- gitea: SSL

SSH_git --- gitea
SSL_git -down- traefik_git
SSL_plantuml -down- traefik_git
SSL_traefik -down- traefik_git
@enduml

@startuml vm-drone
skinparam monochrome true
skinparam defaulttextalignment center

component "Virtual Machine\ndocker" as VM2 {
  component Docker as docker2 {
    artifact "drone/drone:1.0.0-rc.6" as drone_server
    artifact "drone/agent:1.0.0-rc.6" as drone_agent
    artifact "traefik:latest" as traefik_build
    artifact "docker daemon" as docker
  }
  database "Managed\nDisk" as disk2
  drone_server .. disk2: /data/volumes/drone-server
  drone_server .left. docker: /var/run/docker.sock
  traefik_build -- drone_server: 3000
  traefik_build .left. docker: /var/run/docker.sock
}
interface "Traefik dashboard <i>:80,443" as SSL_traefik
interface "Drone Website <i>:80,443" as SSL_drone

SSL_drone -down- traefik_build
SSL_traefik -down- traefik_build
@enduml