@startuml icons-transparent
skinparam monochrome true
skinparam Nodesep 30
skinparam Ranksep 10
rectangle "<size:50><&cloud></size>" as cloud
rectangle "<size:50><&cloudy></size>" as cloudy
rectangle "<size:50><&sun></size>" as sun

sun ->> cloud
cloud ->> cloudy
skinparam rectangleBorderColor none
skinparam rectangleBackgroundColor none
skinparam rectangleShadowing false
@enduml
