kind: pipeline
name: deploy

steps:
- name: prepare
  image: anoff/hugo-asciidoctor
  commands:
  - cp -R theme_fixes/** themes/bilberry-hugo-theme-fork
- name: build
  image: anoff/hugo-asciidoctor
  commands:
  - hugo --gc --minify -d _site --baseURL //blog-gh.anoff.io
  - touch _site/.nojekyll
  - echo "blog-gh.anoff.io" > _site/CNAME
- name: publish  
  image: plugins/gh-pages
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_token
    pages_directory: _site
  when:
    branch:
    - master