language: ruby
rvm:
  - 2.4.1

install: bundle install
script: bundle exec jekyll build

deploy:
  provider: surge
  project: ./_site/
  domain: blog.anoff.io
  skip_cleanup: true

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build
