# Build hugo website and publish to GitHub Pages
#   requires the following Community Plugins
#     https://marketplace.visualstudio.com/items?itemName=giuliovdev.hugo-extension
#     https://marketplace.visualstudio.com/items?itemName=AccidentalFish.githubpages-publish

trigger:
- pipelines

variables:
- group: integration
pool:
  vmImage: 'windows-2019'

steps:
- checkout: self
  displayName: 'Git checkout'
  submodules: true
- script: gem install --no-document asciidoctor asciidoctor-diagram coderay rouge 
  displayName: 'Install Asciidoctor'

- task: HugoTask@1
  displayName: 'Run Hugo'
  inputs:
    destination: 'dist'
    extendedVersion: true
    baseURL: 'https://blog.anoff.io/'

- task: PublishPipelineArtifact@0
  displayName: 'Publish artifact'
  inputs:
    artifactName: 'blog'
    targetPath: 'dist'

- task: NodeTool@0
  displayName: 'Install Node.js'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git clone https://anoff:$(github_token)@github.com/anoff/blog.git --branch=gh-pages ./ghpages
      cd ./ghpages
      git config core.autocrlf false
      git config user.email ""
      git config user.name "CI Joe"
      rm -rf *
      cp -R /d/a/1/s/dist/* . # hardcode directory because pipeline vars are windows
      git add .
      git commit --allow-empty -m 'Automated build #$(Build.BuildNumber)'
      git push
  displayName: 'Publish to gh-pages'