# Build hugo website and publish to GitHub Pages
#   requires the following Community Plugins
#     https://marketplace.visualstudio.com/items?itemName=giuliovdev.hugo-extension
#     https://marketplace.visualstudio.com/items?itemName=AccidentalFish.githubpages-publish

trigger:
- '*'

variables:
- group: integration
- name: 
pool:
  vmImage: 'windows-2019'

steps:
- checkout: self
  displayName: 'Git checkout'
  submodules: true
- script: gem install --no-document asciidoctor asciidoctor-diagram coderay rouge 
  displayName: 'Install Asciidoctor'

- task: HugoTask@1
  displayName: 'Run Hugo'
  inputs:
    destination: '$(Build.ArtifactStagingDirectory)'
    extendedVersion: true
    baseURL: 'https://blog.anoff.io/'

- task: PublishPipelineArtifact@0
  displayName: 'Publish artifact'
  inputs:
    artifactName: 'blog'
    targetPath: '$(Build.ArtifactStagingDirectory)'

- script: |
    git clone https://anoff:$(github_token)@github.com/anoff/blog.git --branch=gh-test $(System.DefaultWorkingDirectory)/ghpages
    cp -R '$(Build.ArtifactStagingDirectory)' $(System.DefaultWorkingDirectory)/ghpages
    cd $(System.DefaultWorkingDirectory)/ghpages
    git config core.autocrlf false
    git config user.email ci@anoff.io
    git config user.name "CI Joe"
    git add *
    git commit --allow-empty -m "Automated build $(Build.BuildId)"
    git push
  displayName: 'Publish to gh-pages'