trigger:
- master

variables:
- group: integration
pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: 'Git checkout'
  submodules: true

- task: Bash@3
  displayName: 'Hotfix theme'
  inputs:
    script: cp -R theme_fixes/** themes/bilberry-hugo-theme

- task: Bash@3
  displayName: 'Build HTML'
  inputs:
    script: |
      docker run --rm -v $PWD:/app anoff/hugo-asciidoctor hugo --gc --minify -d _site
      cp -R _site/* $(Build.ArtifactStagingDirectory)/

- task: PublishPipelineArtifact@0
  displayName: 'Publish artifact'
  inputs:
    artifactName: 'blog'
    targetPath: '$(Build.ArtifactStagingDirectory)'

- task: Bash@3
  inputs:
    script: |
      git clone https://anoff:$(github_token)@github.com/anoff/blog.git --branch=gh-pages ./ghpages
      cd ./ghpages
      git config core.autocrlf false
      git config user.email ""
      git config user.name "CI Joe"
      rm -rf *
      cp -R $(Build.ArtifactStagingDirectory)/* .
      echo blog.anoff.io > CNAME
      git add .
      git commit --allow-empty -m 'Automated build #$(Build.BuildNumber)'
      git push
  displayName: 'Publish to gh-pages'