@startuml
!define COMPANY Andreas Offenhaeuser <anoff.io>
!define YEAR %date[yyyy]%
!define FOOTER © COMPANY YEAR

!define SHADOWING false
!define BORDERTHICKNESS 1
!define NOBORDERTHICKNESS 0

!define ANOFFRED #c03
!define BLACK #000000
!define WHITE #ffffff
!define VALIDATION #78be20
!define WARNING #fcaf17
!define DARKGRAY #333

skinparam ActivityBackgroundColor WHITE
' skinparam ActivityBarColor
skinparam ActivityBorderColor ANOFFRED
skinparam ActivityBorderThickness BORDERTHICKNESS
skinparam ActivityDiamondBackgroundColor WHITE
skinparam ActivityDiamondBorderColor ANOFFRED
skinparam ActivityDiamondFontColor BLACK
' skinparam ActivityDiamondFontName
' skinparam ActivityDiamondFontSize
' skinparam ActivityDiamondFontStyle
' skinparam ActivityEndColor
skinparam ActivityFontColor BLACK
' skinparam ActivityFontName
' skinparam ActivityFontSize
' skinparam ActivityFontStyle
' skinparam ActivityStartColor
skinparam ActorBackgroundColor WHITE
skinparam ActorBorderColor ANOFFRED
skinparam ActorFontColor BLACK
' skinparam ActorFontName
' skinparam ActorFontSize
' skinparam ActorFontStyle
skinparam ActorStereotypeFontColor BLACK
' skinparam ActorStereotypeFontName
' skinparam ActorStereotypeFontSize
' skinparam ActorStereotypeFontStyle
skinparam AgentBackgroundColor WHITE
skinparam AgentBorderColor ANOFFRED
skinparam AgentBorderThickness BORDERTHICKNESS
skinparam AgentFontColor BLACK
' skinparam AgentFontName
' skinparam AgentFontSize
' skinparam AgentFontStyle
skinparam AgentStereotypeFontColor BLACK
' skinparam AgentStereotypeFontName
' skinparam AgentStereotypeFontSize
' skinparam AgentStereotypeFontStyle
skinparam ArrowColor ANOFFRED
skinparam ArrowFontColor BLACK
' skinparam ArrowFontName
' skinparam ArrowFontSize
' skinparam ArrowFontStyle
' skinparam ArrowLollipopColor
' skinparam ArrowMessageAlignment
' skinparam ArrowThickness
skinparam ArtifactBackgroundColor WHITE
skinparam ArtifactBorderColor ANOFFRED
skinparam ArtifactFontColor BLACK
' skinparam ArtifactFontName
' skinparam ArtifactFontSize
' skinparam ArtifactFontStyle
skinparam ArtifactStereotypeFontColor BLACK
' skinparam ArtifactStereotypeFontName
' skinparam ArtifactStereotypeFontSize
' skinparam ArtifactStereotypeFontStyle
skinparam BackgroundColor WHITE
skinparam BiddableBackgroundColor WHITE
skinparam BiddableBorderColor ANOFFRED
skinparam BoundaryBackgroundColor WHITE
skinparam BoundaryBorderColor ANOFFRED
skinparam BoundaryFontColor BLACK
' skinparam BoundaryFontName
' skinparam BoundaryFontSize
' skinparam BoundaryFontStyle
skinparam BoundaryStereotypeFontColor BLACK
' skinparam BoundaryStereotypeFontName
' skinparam BoundaryStereotypeFontSize
' skinparam BoundaryStereotypeFontStyle
skinparam CaptionFontColor BLACK
' skinparam CaptionFontName
' skinparam CaptionFontSize
' skinparam CaptionFontStyle
skinparam CardBackgroundColor WHITE
skinparam CardBorderColor ANOFFRED
skinparam CardBorderThickness BORDERTHICKNESS
skinparam CardFontColor BLACK
' skinparam CardFontName
' skinparam CardFontSize
' skinparam CardFontStyle
skinparam CardStereotypeFontColor BLACK
' skinparam CardStereotypeFontName
' skinparam CardStereotypeFontSize
' skinparam CardStereotypeFontStyle
skinparam CircledCharacterFontColor BLACK
' skinparam CircledCharacterFontName
' skinparam CircledCharacterFontSize
' skinparam CircledCharacterFontStyle
' skinparam CircledCharacterRadius
skinparam ClassAttributeFontColor BLACK
' skinparam ClassAttributeFontName
' skinparam ClassAttributeFontSize
' skinparam ClassAttributeFontStyle
' skinparam ClassAttributeIconSize
skinparam ClassBackgroundColor WHITE
skinparam ClassBorderColor ANOFFRED
skinparam ClassBorderThickness BORDERTHICKNESS
skinparam ClassFontColor BLACK
' skinparam ClassFontName
' skinparam ClassFontSize
' skinparam ClassFontStyle
skinparam ClassHeaderBackgroundColor WHITE
skinparam ClassStereotypeFontColor BLACK
' skinparam ClassStereotypeFontName
' skinparam ClassStereotypeFontSize
' skinparam ClassStereotypeFontStyle
skinparam CloudBackgroundColor WHITE
skinparam CloudBorderColor ANOFFRED
skinparam CloudFontColor BLACK
' skinparam CloudFontName
' skinparam CloudFontSize
' skinparam CloudFontStyle
skinparam CloudStereotypeFontColor BLACK
' skinparam CloudStereotypeFontName
' skinparam CloudStereotypeFontSize
' skinparam CloudStereotypeFontStyle
skinparam CollectionsBackgroundColor WHITE
skinparam CollectionsBorderColor ANOFFRED
' skinparam ColorArrowSeparationSpace
skinparam ComponentBackgroundColor WHITE
skinparam ComponentBorderColor ANOFFRED
skinparam ComponentBorderThickness BORDERTHICKNESS
skinparam ComponentFontColor BLACK
' skinparam ComponentFontName
' skinparam ComponentFontSize
' skinparam ComponentFontStyle
skinparam ComponentStereotypeFontColor BLACK
' skinparam ComponentStereotypeFontName
' skinparam ComponentStereotypeFontSize
' skinparam ComponentStereotypeFontStyle
' skinparam ComponentStyle
' skinparam ConditionStyle
skinparam ControlBackgroundColor WHITE
skinparam ControlBorderColor ANOFFRED
skinparam ControlFontColor BLACK
' skinparam ControlFontName
' skinparam ControlFontSize
' skinparam ControlFontStyle
skinparam ControlStereotypeFontColor BLACK
' skinparam ControlStereotypeFontName
' skinparam ControlStereotypeFontSize
' skinparam ControlStereotypeFontStyle
skinparam DatabaseBackgroundColor WHITE
skinparam DatabaseBorderColor ANOFFRED
skinparam DatabaseFontColor BLACK
' skinparam DatabaseFontName
' skinparam DatabaseFontSize
' skinparam DatabaseFontStyle
skinparam DatabaseStereotypeFontColor BLACK
' skinparam DatabaseStereotypeFontName
' skinparam DatabaseStereotypeFontSize
' skinparam DatabaseStereotypeFontStyle
skinparam DefaultFontColor BLACK
' skinparam DefaultFontName
' skinparam DefaultFontSize
' skinparam DefaultFontStyle
' skinparam DefaultMonospacedFontName
skinparam DefaultTextAlignment center
skinparam DesignedBackgroundColor WHITE
skinparam DesignedBorderColor ANOFFRED
skinparam DesignedDomainBorderThickness BORDERTHICKNESS
skinparam DesignedDomainFontColor BLACK
' skinparam DesignedDomainFontName
' skinparam DesignedDomainFontSize
' skinparam DesignedDomainFontStyle
skinparam DesignedDomainStereotypeFontColor BLACK
' skinparam DesignedDomainStereotypeFontName
' skinparam DesignedDomainStereotypeFontSize
' skinparam DesignedDomainStereotypeFontStyle
skinparam DiagramBorderColor WHITE
skinparam DiagramBorderThickness NOBORDERTHICKNESS
skinparam DomainBackgroundColor WHITE
skinparam DomainBorderColor ANOFFRED
skinparam DomainBorderThickness BORDERTHICKNESS
skinparam DomainFontColor BLACK
' skinparam DomainFontName
' skinparam DomainFontSize
' skinparam DomainFontStyle
skinparam DomainStereotypeFontColor BLACK
' skinparam DomainStereotypeFontName
' skinparam DomainStereotypeFontSize
' skinparam DomainStereotypeFontStyle
' skinparam Dpi
skinparam EntityBackgroundColor WHITE
skinparam EntityBorderColor ANOFFRED
skinparam EntityFontColor BLACK
' skinparam EntityFontName
' skinparam EntityFontSize
' skinparam EntityFontStyle
skinparam EntityStereotypeFontColor BLACK
' skinparam EntityStereotypeFontName
' skinparam EntityStereotypeFontSize
' skinparam EntityStereotypeFontStyle
skinparam FileBackgroundColor WHITE
skinparam FileBorderColor ANOFFRED
skinparam FileFontColor BLACK
' skinparam FileFontName
' skinparam FileFontSize
' skinparam FileFontStyle
skinparam FileStereotypeFontColor BLACK
' skinparam FileStereotypeFontName
' skinparam FileStereotypeFontSize
' skinparam FileStereotypeFontStyle
skinparam FolderBackgroundColor WHITE
skinparam FolderBorderColor ANOFFRED
skinparam FolderFontColor BLACK
' skinparam FolderFontName
' skinparam FolderFontSize
' skinparam FolderFontStyle
skinparam FolderStereotypeFontColor BLACK
' skinparam FolderStereotypeFontName
' skinparam FolderStereotypeFontSize
' skinparam FolderStereotypeFontStyle
skinparam FooterFontColor DARKGRAY
' skinparam FooterFontName
' skinparam FooterFontSize
' skinparam FooterFontStyle
skinparam FrameBackgroundColor WHITE
skinparam FrameBorderColor ANOFFRED
skinparam FrameFontColor BLACK
' skinparam FrameFontName
' skinparam FrameFontSize
' skinparam FrameFontStyle
skinparam FrameStereotypeFontColor BLACK
' skinparam FrameStereotypeFontName
' skinparam FrameStereotypeFontSize
' skinparam FrameStereotypeFontStyle
' skinparam GenericDisplay
' skinparam Guillemet
' skinparam Handwritten
skinparam HeaderFontColor BLACK
' skinparam HeaderFontName
' skinparam HeaderFontSize
' skinparam HeaderFontStyle
' skinparam HyperlinkColor
' skinparam HyperlinkUnderline
' skinparam IconIEMandatoryColor
skinparam IconPackageBackgroundColor WHITE
' skinparam IconPackageColor
skinparam IconPrivateBackgroundColor WHITE
' skinparam IconPrivateColor
skinparam IconProtectedBackgroundColor WHITE
' skinparam IconProtectedColor
skinparam IconPublicBackgroundColor WHITE
' skinparam IconPublicColor
skinparam InterfaceBackgroundColor WHITE
skinparam InterfaceBorderColor ANOFFRED
skinparam InterfaceFontColor BLACK
' skinparam InterfaceFontName
' skinparam InterfaceFontSize
' skinparam InterfaceFontStyle
skinparam InterfaceStereotypeFontColor BLACK
' skinparam InterfaceStereotypeFontName
' skinparam InterfaceStereotypeFontSize
' skinparam InterfaceStereotypeFontStyle
skinparam LegendBackgroundColor WHITE
skinparam LegendBorderColor ANOFFRED
skinparam LegendBorderThickness BORDERTHICKNESS
skinparam LegendFontColor BLACK
' skinparam LegendFontName
' skinparam LegendFontSize
' skinparam LegendFontStyle
skinparam LexicalBackgroundColor WHITE
skinparam LexicalBorderColor ANOFFRED
' skinparam Linetype
skinparam MachineBackgroundColor WHITE
skinparam MachineBorderColor ANOFFRED
skinparam MachineBorderThickness BORDERTHICKNESS
skinparam MachineFontColor BLACK
' skinparam MachineFontName
' skinparam MachineFontSize
' skinparam MachineFontStyle
skinparam MachineStereotypeFontColor BLACK
' skinparam MachineStereotypeFontName
' skinparam MachineStereotypeFontSize
' skinparam MachineStereotypeFontStyle
' skinparam MaxAsciiMessageLength
' skinparam MaxMessageSize
' skinparam MinClassWidth
' skinparam Monochrome
skinparam NodeBackgroundColor WHITE
skinparam NodeBorderColor ANOFFRED
skinparam NodeFontColor BLACK
' skinparam NodeFontName
' skinparam NodeFontSize
' skinparam NodeFontStyle
skinparam NodeStereotypeFontColor BLACK
' skinparam NodeStereotypeFontName
' skinparam NodeStereotypeFontSize
' skinparam NodeStereotypeFontStyle
' skinparam Nodesep
skinparam NoteBackgroundColor WHITE
skinparam NoteBorderColor ANOFFRED
skinparam NoteBorderThickness BORDERTHICKNESS
skinparam NoteFontColor BLACK
' skinparam NoteFontName
' skinparam NoteFontSize
' skinparam NoteFontStyle
' skinparam NoteShadowing
' skinparam NoteTextAlignment
skinparam ObjectAttributeFontColor BLACK
' skinparam ObjectAttributeFontName
' skinparam ObjectAttributeFontSize
' skinparam ObjectAttributeFontStyle
skinparam ObjectBackgroundColor WHITE
skinparam ObjectBorderColor ANOFFRED
skinparam ObjectBorderThickness BORDERTHICKNESS
skinparam ObjectFontColor BLACK
' skinparam ObjectFontName
' skinparam ObjectFontSize
' skinparam ObjectFontStyle
skinparam ObjectStereotypeFontColor BLACK
' skinparam ObjectStereotypeFontName
' skinparam ObjectStereotypeFontSize
' skinparam ObjectStereotypeFontStyle
skinparam PackageBackgroundColor WHITE
skinparam PackageBorderColor ANOFFRED
skinparam PackageBorderThickness BORDERTHICKNESS
skinparam PackageFontColor BLACK
' skinparam PackageFontName
' skinparam PackageFontSize
' skinparam PackageFontStyle
skinparam PackageStereotypeFontColor BLACK
' skinparam PackageStereotypeFontName
' skinparam PackageStereotypeFontSize
' skinparam PackageStereotypeFontStyle
' skinparam PackageStyle
' skinparam PackageTitleAlignment
' skinparam Padding
skinparam PageBorderColor ANOFFRED
' skinparam PageExternalColor
' skinparam PageMargin
skinparam ParticipantBackgroundColor WHITE
skinparam ParticipantBorderColor ANOFFRED
skinparam ParticipantFontColor BLACK
' skinparam ParticipantFontName
' skinparam ParticipantFontSize
' skinparam ParticipantFontStyle
skinparam PartitionBackgroundColor WHITE
skinparam PartitionBorderColor ANOFFRED
skinparam PartitionBorderThickness BORDERTHICKNESS
skinparam PartitionFontColor BLACK
' skinparam PartitionFontName
' skinparam PartitionFontSize
' skinparam PartitionFontStyle
' skinparam PathHoverColor
skinparam QueueBackgroundColor WHITE
skinparam QueueBorderColor ANOFFRED
skinparam QueueFontColor BLACK
' skinparam QueueFontName
' skinparam QueueFontSize
' skinparam QueueFontStyle
skinparam QueueStereotypeFontColor BLACK
' skinparam QueueStereotypeFontName
' skinparam QueueStereotypeFontSize
' skinparam QueueStereotypeFontStyle
' skinparam Ranksep
skinparam RectangleBackgroundColor WHITE
skinparam RectangleBorderColor ANOFFRED
skinparam RectangleBorderThickness BORDERTHICKNESS
skinparam RectangleFontColor BLACK
' skinparam RectangleFontName
' skinparam RectangleFontSize
' skinparam RectangleFontStyle
skinparam RectangleStereotypeFontColor BLACK
' skinparam RectangleStereotypeFontName
' skinparam RectangleStereotypeFontSize
' skinparam RectangleStereotypeFontStyle
skinparam RequirementBackgroundColor WHITE
skinparam RequirementBorderColor ANOFFRED
skinparam RequirementBorderThickness BORDERTHICKNESS
skinparam RequirementFontColor BLACK
' skinparam RequirementFontName
' skinparam RequirementFontSize
' skinparam RequirementFontStyle
skinparam RequirementStereotypeFontColor BLACK
' skinparam RequirementStereotypeFontName
' skinparam RequirementStereotypeFontSize
' skinparam RequirementStereotypeFontStyle
' skinparam ResponseMessageBelowArrow
skinparam RoundCorner 0
' skinparam SameClassWidth
skinparam SequenceActorBorderThickness BORDERTHICKNESS
' skinparam SequenceArrowThickness
skinparam SequenceBoxBackgroundColor WHITE
skinparam SequenceBoxBorderColor ANOFFRED
skinparam SequenceBoxFontColor BLACK
' skinparam SequenceBoxFontName
' skinparam SequenceBoxFontSize
' skinparam SequenceBoxFontStyle
skinparam SequenceDelayFontColor BLACK
' skinparam SequenceDelayFontName
' skinparam SequenceDelayFontSize
' skinparam SequenceDelayFontStyle
skinparam SequenceDividerBackgroundColor WHITE
skinparam SequenceDividerBorderColor ANOFFRED
skinparam SequenceDividerBorderThickness BORDERTHICKNESS
skinparam SequenceDividerFontColor BLACK
' skinparam SequenceDividerFontName
' skinparam SequenceDividerFontSize
' skinparam SequenceDividerFontStyle
skinparam SequenceGroupBackgroundColor WHITE
skinparam SequenceGroupBodyBackgroundColor WHITE
skinparam SequenceGroupBorderColor ANOFFRED
skinparam SequenceGroupBorderThickness BORDERTHICKNESS
skinparam SequenceGroupFontColor BLACK
' skinparam SequenceGroupFontName
' skinparam SequenceGroupFontSize
' skinparam SequenceGroupFontStyle
skinparam SequenceGroupHeaderFontColor BLACK
' skinparam SequenceGroupHeaderFontName
' skinparam SequenceGroupHeaderFontSize
' skinparam SequenceGroupHeaderFontStyle
skinparam SequenceLifeLineBackgroundColor WHITE
skinparam SequenceLifeLineBorderColor ANOFFRED
skinparam SequenceLifeLineBorderThickness BORDERTHICKNESS
' skinparam SequenceMessageAlignment
' skinparam SequenceMessageTextAlignment
' skinparam SequenceNewpageSeparatorColor
' skinparam SequenceParticipant
skinparam SequenceParticipantBorderThickness BORDERTHICKNESS
' skinparam SequenceReferenceAlignment
skinparam SequenceReferenceBackgroundColor WHITE
skinparam SequenceReferenceBorderColor ANOFFRED
skinparam SequenceReferenceBorderThickness BORDERTHICKNESS
skinparam SequenceReferenceFontColor BLACK
' skinparam SequenceReferenceFontName
' skinparam SequenceReferenceFontSize
' skinparam SequenceReferenceFontStyle
skinparam SequenceReferenceHeaderBackgroundColor WHITE
skinparam SequenceStereotypeFontColor BLACK
' skinparam SequenceStereotypeFontName
' skinparam SequenceStereotypeFontSize
' skinparam SequenceStereotypeFontStyle
skinparam SequenceTitleFontColor BLACK
' skinparam SequenceTitleFontName
' skinparam SequenceTitleFontSize
' skinparam SequenceTitleFontStyle
skinparam Shadowing SHADOWING
skinparam StackBackgroundColor WHITE
skinparam StackBorderColor ANOFFRED
skinparam StackFontColor BLACK
' skinparam StackFontName
' skinparam StackFontSize
' skinparam StackFontStyle
skinparam StackStereotypeFontColor BLACK
' skinparam StackStereotypeFontName
' skinparam StackStereotypeFontSize
' skinparam StackStereotypeFontStyle
skinparam StateAttributeFontColor BLACK
' skinparam StateAttributeFontName
' skinparam StateAttributeFontSize
' skinparam StateAttributeFontStyle
skinparam StateBackgroundColor WHITE
skinparam StateBorderColor ANOFFRED
' skinparam StateEndColor
skinparam StateFontColor BLACK
' skinparam StateFontName
' skinparam StateFontSize
' skinparam StateFontStyle
' skinparam StateStartColor
skinparam StereotypeABackgroundColor WHITE
skinparam StereotypeABorderColor ANOFFRED
skinparam StereotypeCBackgroundColor WHITE
skinparam StereotypeCBorderColor ANOFFRED
skinparam StereotypeEBackgroundColor WHITE
skinparam StereotypeEBorderColor ANOFFRED
skinparam StereotypeIBackgroundColor WHITE
skinparam StereotypeIBorderColor ANOFFRED
skinparam StereotypeNBackgroundColor WHITE
skinparam StereotypeNBorderColor ANOFFRED
' skinparam StereotypePosition
skinparam StorageBackgroundColor WHITE
skinparam StorageBorderColor ANOFFRED
skinparam StorageFontColor BLACK
' skinparam StorageFontName
' skinparam StorageFontSize
' skinparam StorageFontStyle
skinparam StorageStereotypeFontColor BLACK
' skinparam StorageStereotypeFontName
' skinparam StorageStereotypeFontSize
' skinparam StorageStereotypeFontStyle
' skinparam Style
' skinparam SvglinkTarget
skinparam SwimlaneBorderColor ANOFFRED
skinparam SwimlaneBorderThickness BORDERTHICKNESS
skinparam SwimlaneTitleFontColor BLACK
' skinparam SwimlaneTitleFontName
' skinparam SwimlaneTitleFontSize
' skinparam SwimlaneTitleFontStyle
' skinparam SwimlaneWidth
' skinparam SwimlaneWrapTitleWidth
' skinparam TabSize
skinparam TitleBackgroundColor WHITE
skinparam TitleBorderColor WHITE
skinparam TitleBorderRoundCorner NOBORDERTHICKNESS
skinparam TitleBorderThickness BORDERTHICKNESS
skinparam TitleFontColor ANOFFRED
' skinparam TitleFontName
' skinparam TitleFontSize
' skinparam TitleFontStyle
skinparam UsecaseBackgroundColor WHITE
skinparam UsecaseBorderColor ANOFFRED
skinparam UsecaseBorderThickness BORDERTHICKNESS
skinparam UsecaseFontColor BLACK
' skinparam UsecaseFontName
' skinparam UsecaseFontSize
' skinparam UsecaseFontStyle
skinparam UsecaseStereotypeFontColor BLACK
' skinparam UsecaseStereotypeFontName
' skinparam UsecaseStereotypeFontSize
' skinparam UsecaseStereotypeFontStyle
' skinparam WrapWidth

center footer FOOTER
@enduml