@startuml architecture
!include <font-awesome/common>
!include <devicons/firebase>
!includeurl https://gist.githubusercontent.com/anoff/c531251183cf9590b0f86ac85d5bc353/raw/fancy.plantuml
skinparam defaultTextAlignment center

node "Web App\n(Browser)" as app
actor "User" as user

DEV_FIREBASE(db, database, database)
DEV_FIREBASE(auth, auth provider, component)

user ->> app
app ->> db
app -down->> auth
@enduml