---
title: Hosting Gitea and Drone with Docker
date: 2019-03-24
tags: [azure, gitea, drone, CI/CD]
author: anoff
resizeImages: true
featuredImage: /
draft: true
---
:plantuml-server-url: http://plantuml.com/plantuml
:toc:

This post will walk you through setting up a self hosted git based continuous integration environment on a two machine setup - assuming you already have two virtual machines with `docker-compose` at your disposal. Using `Gitea` for git hosting and contribution management and drone.io for docker-based build jobs, this will guide you through creating **docker-compose** files as well as configuring the individual services and getting **SSL certificates** via `traefik`.

== Prerequisites

For this to work you need two virtual machines (commands for Ubuntu) and a PostgreSQL database. I used the following Azure services for this setup:

- Azure PostgreSQL Server
  - Postgres v10.0
  - 70 GB storage
  - 1 vCores
  - attached data disk (managed disk)
- 2x VM Ubuntu
  - Standard A2 v2 (2 vCPUs, 4 GB memory)

[plantuml, vm-setup, svg]
....
@startuml VM-setup
skinparam monochrome true
skinparam defaulttextalignment center

frame "Virtual Network" as VNET {
  frame "Subnet" as subnet {
    component "Virtual Machine\ngitea" as VM1 {
      database "Managed\nDisk" as disk1
    }

    component "Virtual Machine\ndrone" as VM2 {
      database "Managed\nDisk" as disk2
    }
  }
}

database "Azure\nPostgreSQL" as psql
VM1 -- psql
@enduml
....


[plantuml, gitea-setup, svg]
....
@startuml VM-gitea
skinparam monochrome true
skinparam defaulttextalignment center

component "Virtual Machine\ngitea" as VM1 {
  component Docker as docker1 {
    artifact "gitea/gitea:latest" as gitea
    artifact "traefik:latest" as traefik_git
    artifact "plantuml/plantuml-server:jetty" as plantuml
    artifact "docker daemon" as docker
  }
  database "Managed\nDisk" as disk1
  gitea .. disk1: /data/volumes/gitea
  traefik_git .. disk1: /data/volumes/traefik
  traefik_git .left. docker: /var/run/docker.sock
  traefik_git -- gitea: 3000
  traefik_git -- plantuml: 8080
}

database "Azure\nPostgreSQL" as psql
interface "Gitea Website <i>:80,443" as SSL_git
interface "Gitea git <i>:22" as SSH_git
interface "PlantUML <i>:80,443" as SSL_plantuml

psql -up- gitea: SSL

SSH_git --- gitea
SSL_git -down- traefik_git
SSL_plantuml -down- traefik_git

@enduml
....


[plantuml, drone-setup, png]
....
@startuml VM-drone
skinparam monochrome true
skinparam defaulttextalignment center

component "Virtual Machine\ndocker" as VM2 {
  component Docker as docker2 {
    artifact "drone/drone:1.0.0-rc.6" as drone_server
    artifact "drone/agent:1.0.0-rc.6" as drone_agent
    artifact "traefik:latest" as traefik_build
    artifact "docker daemon" as docker
  }
  database "Managed\nDisk" as disk2
  drone_server .. disk2: /data/volumes/drone-server
  drone_server .left. docker: /var/run/docker.sock
  traefik_build -- drone_server: 3000
  traefik_build .left. docker: /var/run/docker.sock
}
interface "Traefik dashboard <i>:80,443" as SSL_traefik
interface "Drone Website <i>:80,443" as SSL_drone

SSL_drone -down- traefik_build
SSL_traefik -down- traefik_build
@enduml
....

== Prepare PostgreSQL

Create database & role for GitLab system user.  Works via [Azure Cloud shell](https://shell.azure.com) after activating _Allow access to Azure services_ in the _Connection Security_ pane of the resource.

[source,bash]
----
psql --host=mydb.postgres.database.azure.com --port=5432 --username=machina@mydb --dbname=postgres
# interactive password login
CREATE EXTENSION pg_trgm;
CREATE ROLE gitea with LOGIN CREATEDB PASSWORD 'supersexypassword';
CREATE DATABASE gitea;
GRANT ALL PRIVILEGES ON DATABASE gitea to gitea;
----

== VM Setup

For each virtual machine we will do the following steps to 

. Change SSH port to 2022
. Install Docker & docker-compose
. Format & auto mount data disk
. create docker user "servus"

[source,bash]
----
# Docker
#   https://docs.docker.com/install/linux/docker-ce/ubuntu/
sudo apt-get remove docker docker-engine docker.io containerd runc
sudo apt-get update
sudo apt-get -y install \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg-agent \
  software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get -y install docker-ce docker-ce-cli containerd.io

# Compose
#   https://docs.docker.com/compose/install/
sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
----

=== Mount data disk

`lsblk`: Find available disks

[source,bash]
----
sudo -s # enter root mode
DATA_DISK=/dev/sdc
# Mount data disk, xfs will not encrypt
mkfs.ext4 ${DATA_DISK}

# identify UUID: blkid -s UUID
DATA_DISK_UUID=$(blkid -s UUID -o value ${DATA_DISK})
mkdir /data
# Add line to /etc/fstab
echo "UUID=${DATA_DISK_UUID} /data auto defaults 0 0" >> /etc/fstab
mount -a
exit
----

See also [Azure help](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/attach-disk-portal)

=== Create docker user

```sh
sudo -s
mkdir /data/home
mkdir /data/volumes
useradd -d /data/home servus
chown servus: /data/home -R
chown servus: /data/volumes/ -R
# give docker access
gpasswd -a servus docker
exit
# find user ID
id servus
```

=== Change SSH port

[source,bash]
----
sudo nano /etc/ssh/sshd_config
# uncomment and change L3: Port 2022
----

== Traefik setup