@startuml icons-transparent
skinparam monochrome false
skinparam Nodesep 30
skinparam Ranksep 10
!include <font-awesome/common>
!include <font-awesome/cogs>
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.0.0
!includeurl ICONURL/govicons/submarine.puml
FA_COGS(c1, work) #white
GOV_SUBMARINE(sub1, Submarine1) #lightblue
GOV_SUBMARINE(sub2, , frame, red) {
  FA_COGS(c2, more work, card, white) #limegreen
}
@enduml
